
GOOGLE_APP_ID: '922871847889-4gjvn4c4ndfvnrcumiv0032n94taq5bj.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'fhdikm_dfLddw5P5RNqj94My'

GOOGLE_RECAPT_SITE_KEY: '6LcVvjQUAAAAAPt291eFG1Z8qwHbP2QHwCPRLpqi'
GOOGLE_RECAPT_SECRET_KEY: '6LcVvjQUAAAAABkCuL3f_xop4bCw3gnkwmQqIv5K'

FACEBOOK_APP_ID: '122293051774342'
FACEBOOK_APP_SECRET: '57c9df7b49d1df7f61a69765ab2be129'

TWITTER_API_KEY: '0Q5AjKpuSWxbKfNHxXio3xIyu'
TWITTER_API_SECRET: 'kX8KShRo5cSRvVKHnlMx3KjOoGp9yYkRNKu6H4W5PsKErjJNCU'

AWS_SES_USERNAME: 'AKIAJB6TE62WHKLEU3RQ'
AWS_SES_PASSWORD: 'Am2UStoef2+ZNfP+RMW8pkehJN9pxehJq2m9QszmEI7D'
AWS_SES_SMTP: 'email-smtp.us-east-1.amazonaws.com'

AWS_S3_BUCKET:  'shop-demo'
AWS_ACCESS_KEY_ID: 'AKIAJTUKASASP2TU5PSA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_S3_REGION: 'us-east-1'

