GOOGLE_APP_ID: '922871847889-4gjvn4c4ndfvnrcumiv0032n94taq5bj.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'fhdikm_dfLddw5P5RNqj94My'

GOOGLE_RECAPT_SITE_KEY: '6LcVvjQUAAAAAPt291eFG1Z8qwHbP2QHwCPRLpqi'
GOOGLE_RECAPT_SECRET_KEY: '6LcVvjQUAAAAABkCuL3f_xop4bCw3gnkwmQqIv5K'

FACEBOOK_APP_ID: '122293051774342'
FACEBOOK_APP_SECRET: '57c9df7b49d1df7f61a69765ab2be129'

TWITTER_API_KEY: '0Q5AjKpuSWxbKfNHxXio3xIyu'
TWITTER_API_SECRET: 'kX8KShRo5cSRvVKHnlMx3KjOoGp9yYkRNKu6H4W5PsKErjJNCU'

AWS_SES_USERNAME: 'AKIAJB6TE62WHKLEU3RQ'
AWS_SES_PASSWORD: 'Am2UStoef2+ZNfP+RMW8pkehJN9pxehJq2m9QszmEI7D'
AWS_SES_SMTP: 'email-smtp.us-east-1.amazonaws.com'

AWS_S3_BUCKET:  'shop-demo'
AWS_ACCESS_KEY_ID: 'AKIAJTUKASASP2TU5PSA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_S3_REGION: 'us-east-1'

SECRET_CODE_CREATE_ORDER_FROM_EMAIL: 'SKVJSNSCK1232756kadaskLDKWD'

TWO_CHECKOUT_SELLER_ID: '203473499'
TWO_CHECKOUT_SECRET_WORD: 'YzhhMTBkM2QtZmU3Yi00MjlkLWEyNTQtZDExZDdhNGU5OTQ0'

BAO_KIM_CORE_API_HTTP_USR: 'xxxxxxxxxx'
BAO_KIM_CORE_API_HTTP_PWD: 'xxxxxxxxxxxxxxxxx'
BAO_KIM_SECURE_CODE: 'xxxxxxxxxxxxxxxxx'
BAO_KIM_MERCHANT_ID: '123456'
BAO_KIM_API_USERNAME: 'xxxxxx'
BAO_KIM_API_PASSWORD: 'xxxxxxxxxxxxxx'

BAO_KIM_PAYMENT_CART_URL: 'https://www.baokim.vn/payment/order/version11'
BAO_KIM_BUSINESS_ACCOUNT: 'enziinsystem@gmail.com'

BAO_KIM_BPN_LISTENER: 'http://shop.enziin.com/orders/payments/bao-kim/bpn'
BAO_KIM_BPN_VERIFY: 'https://www.baokim.vn/bpn/verify'

BAO_KIM_SUCCESS_CART_URL: 'http://shop.enziin.com/orders/payments/bao-kim/success-cart'
BAO_KIM_CANCEL_CART_URL: 'http://shop.enziin.com/orders'
BAO_KIM_DETAIL_CART_URL: 'http://shop.enziin.com/orders'

RATE_USD_TO_VND: '22000'

FACEBOOK_APP_ID_SHARE_OG_META: '1885108544849776'

ADMIN_USER_DATABASE: 'kevin'
ADMIN_PASSWORD_DATABASE: 'VKD132djsdIUIWCKS'

SECRET_KEY_BASE: '2bdcea2dafbe23545768fnghkjhltg3a54580a260ac59aa66fc04e8b79d3b7fbf4e882386dd5f38305bb9ff1ec613ddc91707522d2a1d2f55e6'



