GOOGLE_APP_ID: '879378259252-jq4eupogjlac3ppecl8lm9d7r7jo6n6j.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'FrOSb3ugs9GR_MsA-mwm0UZt'

FACEBOOK_APP_ID: '455299018157999'
FACEBOOK_APP_SECRET: '49679977c1639d2577066f8549d1199d'
FACEBOOK_APP_ID_SHARE_OG_META: '809142549261531'

TWITTER_API_KEY: 'GNS3QT8xJ083pD9J6yNKRKNmB'
TWITTER_API_SECRET: 'Rhm8VzBaQmN3vMWbKTI3GwJuie1mKh2LwvLgQPAjUy0wvwMXaU'

GITHUB_APP_ID: '1f51b845e3b96ee70c95'
GITHUB_APP_SECRET: 'd1d4d4d5009ddeb5d6ce003921c708c238ebc7d5'

GOOGLE_RECAPT_SITE_KEY: '6LclrzMUAAAAALuvJCCBnaSF0ReFk9qdDsvxT8_b'
GOOGLE_RECAPT_SECRET_KEY: '6LclrzMUAAAAAJkzUW0XlC3V4HpFldObCptkQu5j'

AWS_S3_BUCKET:  'shop-demo'
AWS_ACCESS_KEY_ID: 'AKIAJTUKASASP2TU5PSA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_S3_REGION: 'us-east-1'

AWS_SES_USERNAME: 'AKIAJB6TE62WHKLEU3RQ'
AWS_SES_PASSWORD: 'Am2UStoef2+ZNfP+RMW8pkehJN9pxehJq2m9QszmEI7D'
AWS_SES_SMTP: 'email-smtp.us-east-1.amazonaws.com'

# Thiết lập 2Checkout return link : Header Redirect (Your URL)
# Approved URL : http://shop.enziin.com/payment_2co

TWO_CHECKOUT_SELLER_ID: '103446175'
TWO_CHECKOUT_SECRET_WORD: 'N2QzYmRhM2YtNWIwNy00OTg5LThjNTItNjY1MGEwZmYxMTg0'

ACCOUNT_SUPPORT_SERVICE: 'enziinsystem@gmail.com'

RATE_USD_TO_VND: '20000'

ADMIN_USER_DATABASE: 'kevin'
ADMIN_PASSWORD_DATABASE: 'ksdfjFJ232KFSFKDOK'

GEO_COUNTRY_DATABASE: '/home/kevin/websites/geo_country/GeoLite2-Country.mmdb'

PARTNER_ID_DOI_THE_24: '10653'
SECRET_KEY_DOI_THE_24: "162632214_48131_D247"
LINK_DOI_THE_24: "https://doithe247.com/CardCharge.ashx"

BAO_KIM_CORE_API_HTTP_USR: 'merchant_cxzc'
BAO_KIM_CORE_API_HTTP_PWD: 'xczcxzpGZVYaLt16zUP8kMeOiSQAm47KNCuR'
BAO_KIM_SECURE_CODE: '2d49bd884deb4f42'
BAO_KIM_MERCHANT_ID: '30557'
BAO_KIM_API_USERNAME: 'wwwenziincom'
BAO_KIM_API_PASSWORD: 'wwwenziincomdsadsadas'
BAO_KIM_PHONE_CARD_URL: 'https://www.baokim.vn/the-cao/restFul/send'

BAO_KIM_PAYMENT_CART_URL: 'https://www.baokim.vn/payment/order/version11'
BAO_KIM_BUSINESS_ACCOUNT: 'enziinsystem@gmail.com'
BAO_KIM_SUCCESS_CART_URL: 'http://shop.enziin.com/orders/payments/bao-kim/success-cart'
BAO_KIM_CANCEL_CART_URL: 'http://shop.enziin.com/orders'
BAO_KIM_DETAIL_CART_URL: 'http://shop.enziin.com/orders'
BAO_KIM_BPN_LISTENER: 'http://shop.enziin.com/orders/payments/bao-kim/bpn'
BAO_KIM_BPN_VERIFY: 'https://www.baokim.vn/bpn/verify'

#Tham số cho thanh toán checkout cơ bản
ACCOUNT_HOLDER_NGANLUONG: 'enziinsystem@gmail.com'
RETURN_URL_NGANLUONG: 'http://shop.enziin.com/nganluong/complete'

#Tham số cho thanh toán checkout pro (chưa thực hiện tích hợp)
NGAN_LUONG_MERCHANT_ID: '52136'
NGAN_LUONG_SECRET_CODE: '6b875c2e214fdae85a8e6dd4c0273a5b'
NGAN_LUONG_API_URL: 'https://www.nganluong.vn/checkout.api.nganluong.post.php'
NGAN_LUONG_BUSINESS_ACCOUNT: 'enziinsystem@gmail.com'
NGAN_LUONG_SUCCESS_CART_URL: 'http://shop.enziin.com/orders/payments/ngan-luong/success-cart'
NGAN_LUONG_CANCEL_CART_URL: 'http://shop.enziin.com/orders'

SECRET_CODE_CREATE_ORDER_FROM_EMAIL: 'SDSDSU234U922Dsdfd@@@5$@^&*12'

SECRET_KEY_BASE: '4161cef2a0c735accd6ebc2176301cb071d69319296c069b1a7d4af987a3e27d3d17055eb61ebe81cb955be7ce90c44050b6e47a178e8062ab5c4644e1bd5b3d'
