
GOOGLE_APP_ID: '922871847889-4gjvn4c4ndfvnrcumiv0032n94taq5bj.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'fhdikm_dfLddw5P5RNqj94My'

GOOGLE_RECAPT_SITE_KEY: '6LcVvjQUAAAAAPt291eFG1Z8qwHbP2QHwCPRLpqi'
GOOGLE_RECAPT_SECRET_KEY: '6LcVvjQUAAAAABkCuL3f_xop4bCw3gnkwmQqIv5K'

FACEBOOK_APP_ID: '129378877719968'
FACEBOOK_APP_SECRET: 'ca78101bdb4cab5e42a38e5a47e7052a'

TWITTER_API_KEY: '0Q5AjKpuSWxbKfNHxXio3xIyu'
TWITTER_API_SECRET: 'kX8KShRo5cSRvVKHnlMx3KjOoGp9yYkRNKu6H4W5PsKErjJNCU'
